name: 'Setup Haxe environment'
description: 'Setup a Haxe environment and add it to the PATH'
author: 'Sho Kuroda <krdlab@gmail.com>'
inputs:
  haxe-version:
    description: 'Version Spec of the version to use. Example: 4.2.2'
    required: true
    default: '4.2.4'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'download'
  color: 'gray-dark'
